name: ControlAnticheat
version: 0.5
author: Valorit
main: de.valorit.cac.Main

commands:
  cac:
    description: The main command
  ping:
    description: Displays the ping of yourself or of another player